### ISSUE TITLE
chalk orange does not exists

### ISSUE THREAD

**Issue by psi-4ward** [ekoeryanto/vuepress-plugin-sitemap#10]
```
TypeError: chalk.reset.inverse.bold[color] is not a function
```
happens when `color='orange'`

**Comment by ekoeryanto** [comment]
Hi, I'm sorry. But I can't reproduce the issue, can you provide more info, your OS maybe?

**Comment by psi-4ward** [comment]
linux on node 11.6

if I use color=red it works perfectly. 
Looks like ansi doesnt support orange: https://www.npmjs.com/package/ansi-styles#colors

**Comment by ekoeryanto** [comment]
If so, then we need to change it to red.
I hope you willing to make a PR for this

**Comment by psi-4ward** [comment]
changing one word is not too difficult :)
