### ISSUE TITLE
does not work with localized date

### ISSUE THREAD

**Issue by psi-4ward** [ekoeryanto/vuepress-plugin-sitemap#11]
```
  locales: {
    "/": {
      lang: "de-DE"
    }
  },
```

sets `page.lastUpdated` to dates like:
* 2.1.2019, 12:17:10
* 28.12.2018, 03:29:42

which can't be use in new Date()

**Comment by ekoeryanto** [comment]
Hi, thanks for the issue.
Can you please, create the PR to fix in here?

**Comment by psi-4ward** [comment]
sure, but it depends on https://github.com/psi-4ward/vuepress/pull/1 so lets wait whats going on with this one

**Comment by ekoeryanto** [comment]
I think it solved with `dateFormatter` option in v2.3.0

**Comment by psi-4ward** [comment]
It's not very comfortable that we have to implement our own reverse-dete-formatter, especially if we have more than one date (ie in multilang websites). I still would prefer a the `lastUpdateTstamp` solution. What do you think?

**Comment by ekoeryanto** [comment]
@psi-4ward, i agree with you.
please finish the PR
