### ISSUE TITLE
hostname带路径，解析成的xml文件里面没有路径

### ISSUE THREAD

**Issue by tu6ge** [ekoeryanto/vuepress-plugin-sitemap#26]
```
[
                'sitemap',
                {
                    hostname: 'https://tu6ge.github.io/api-show/'
                }
            ]
```
如上配置，
结果生成的xml文件，内容是这样的
`<loc>https://tu6ge.github.io/guide/quickstart.html</loc>`
应该生成的路径是`<loc>https://tu6ge.github.io/api-show/guide/quickstart.html</loc>`

**Comment by ekoeryanto** [comment]
I'm going to check this today.

**Comment by ekoeryanto** [comment]
hello, it fixed ~but not released yet~.
~you can try it with~
```bash
# npm i github:ekoeryanto/vuepress-plugin-sitemap
```
EDIT:
it released now :flower_playing_cards: 

Thanks for reporting the issue.
