### ISSUE TITLE
Doc enhancement

### ISSUE THREAD

**Issue by Mister-Hope** [ekoeryanto/vuepress-plugin-sitemap#32]
The doc in readme is too simple. 

E.g.: the param `time` in the dateFormat function, we don't know what's it unless we read through the code.

**Comment by saleh-old** [comment]
I couldn't even get it started. I installed and here is my plugins in the config file:
```
    plugins: [
        '@vuepress/medium-zoom',
        [
            '@vuepress/google-analytics',
            {
                ga: 'UA-135004813-1',
            },
        ],
        [
            'sitemap',
            {
                hostname: 'https://docs.jesse-ai.com',
            },
        ],
    ],
```

Am I missing something?

**Comment by Mister-Hope** [comment]
> I couldn't even get it started. I installed and here is my plugins in the config file:
> 
> ```
>     plugins: [
>         '@vuepress/medium-zoom',
>         [
>             '@vuepress/google-analytics',
>             {
>                 ga: 'UA-135004813-1',
>             },
>         ],
>         [
>             'sitemap',
>             {
>                 hostname: 'https://docs.jesse-ai.com',
>             },
>         ],
>     ],
> ```
> 
> Am I missing something?

What's the error log?

**Comment by saleh-old** [comment]
@Mister-Hope there's no error, I just can't seem to find the sitemap if there's any. I expected to be present at:
http://localhost:8080/sitemap.xml

Am I missing something?

**Comment by Mister-Hope** [comment]
The sitemap is only generated when building

**Comment by PatrickSUDO** [comment]
I cannot generate a sitemap when building either.

```
plugins: [
    ['cursor-effects'],
    ['seo'],
    // ['@vuepress/plugin-blog'],
    ['vuepress-plugin-mathjax'],
    ['vuepress-plugin-disqus'],
    ['sitemap', 
    {
      hostname:'https://patricksudo.github.io'
    },
  ],
    // ['vuepress-plugin-auto-sidebar'],   
],
```

![image](https://user-images.githubusercontent.com/48519645/98045648-b6d2ff00-1e20-11eb-8a27-6b38ee600716.png)

**Comment by Mister-Hope** [comment]
Since this plugin is not maintained. You can try `@mr-hope/vuepress-plugin-sitemap`

https://vuepress-theme-hope.github.io/sitemap/

**Comment by PatrickSUDO** [comment]
Thanks, your plugin works, really helpful.
