### ISSUE TITLE
Enhance in dateFormatter

### ISSUE THREAD

**Issue by Mister-Hope** [ekoeryanto/vuepress-plugin-sitemap#33]
`@vuepress/plugin-last-updated` allow us to edit the text generated to the `lastUpdate` key on page,
for me I am using:

```js
    [
      '@vuepress/last-updated',
      {
        transformer: (timestamp: number, lang: string): string => {
          moment.locale(lang);

          return `${moment(timestamp).format('LL')} ${moment(timestamp).format(
            'HH:mm'
          )}`;
        }
      }
    ],
```

And my `lastUpdated` are `2020年4月30日 12:46` `April 30, 2020 12:46`

Currently, there is NO WAY I can get the timeStamp back throught these string, so can we add a option which allow us to read from git directly?

**Comment by Mister-Hope** [comment]
@ekoeryanto Are you still maintaining it?

**Comment by b0g3r** [comment]
I think it's a good idea to replace `dateFormatter` to a `(page) => {...}` func, so anyone has full control of data when transforms date

**Comment by Mister-Hope** [comment]
yes, I agree with that, meanwhile I am developing a sitemap plugin for my own.

**Comment by ekoeryanto** [comment]
Hello @Mister-Hope PR would be great.

**Comment by Mister-Hope** [comment]
I write a plugin based on sitemapV6 with Stream.  It's called @mr-hope/vuepress-plugin-sitemap. And I am busy these days, so I guess I won't open a PR.
